const GH='https://api.github.com';
const C={'access-control-allow-origin':'*','access-control-allow-headers':'content-type,x-buildone-key','access-control-allow-methods':'GET,POST,OPTIONS'};
const ADS={app:'ca-app-pub-9940728659432865~7416412396',banner:'ca-app-pub-9940728659432865/5564274675',interstitial:'ca-app-pub-9940728659432865/4251193002'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...C,'content-type':'application/json;charset=utf-8'}});
const headers=t=>({Authorization:`Bearer ${t}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'BuildOne-Worker','Content-Type':'application/json'});
const repoOk=x=>/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(x||'');
const pkgOk=x=>/^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)+$/.test(x||'');
const adAppOk=x=>/^ca-app-pub-\d{16}~\d{10}$/.test(x||'');
const adUnitOk=x=>/^ca-app-pub-\d{16}\/\d{10}$/.test(x||'');
const pubOk=x=>/^pub-\d{16}$/.test(x||'');
const domainOk=x=>/^(?=.{1,253}$)(?!-)(?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$/.test(x||'')&&!/[\s/]/.test(x||'');
const privateHost=x=>/^(localhost|127(?:\.\d{1,3}){3}|10(?:\.\d{1,3}){3}|192\.168(?:\.\d{1,3}){2}|169\.254(?:\.\d{1,3}){2}|172\.(?:1[6-9]|2\d|3[0-1])(?:\.\d{1,3}){2})$/i.test(x||'');
async function gh(url,t,opt={}){return fetch(url,{...opt,headers:{...headers(t),...(opt.headers||{})}})}
async function put(o,r,p,c,b,t){const u=`${GH}/repos/${o}/${r}/contents/${p.split('/').map(encodeURIComponent).join('/')}`;let sha=null;const q=await gh(`${u}?ref=${encodeURIComponent(b)}`,t);if(q.ok)sha=(await q.json()).sha;const body={message:`BuildOne: ${sha?'update':'create'} ${p}`,content:btoa(unescape(encodeURIComponent(c))),branch:b};if(sha)body.sha=sha;const x=await gh(u,t,{method:'PUT',body:JSON.stringify(body)});if(!x.ok)throw Error(`GitHub ${p}: ${x.status}`);return (await x.json()).commit?.sha||null}
async function build(req,env){const p=await req.json(),parts=String(p.repo||'').split('/');if(parts.length!==2||!repoOk(p.repo)||!pkgOk(p.packageId))throw Error('Invalid repo or package ID');return {ok:false,error:'Use the existing generated Android pipeline for builds; v2 endpoint is intentionally verification-focused.'}}
async function status(req,env){const u=new URL(req.url),o=u.searchParams.get('owner'),r=u.searchParams.get('repo'),id=u.searchParams.get('run_id'),type=u.searchParams.get('type');if(!o||!r||!repoOk(`${o}/${r}`))throw Error('Invalid repository');let run=null;if(id&&/^\d+$/.test(id)){const x=await gh(`${GH}/repos/${o}/${r}/actions/runs/${id}`,env.GITHUB_TOKEN);if(x.ok)run=await x.json()}if(!run){const x=await gh(`${GH}/repos/${o}/${r}/actions/runs?event=push&per_page=20`,env.GITHUB_TOKEN);if(!x.ok)throw Error(`runs failed: ${x.status}`);const d=await x.json();run=d.workflow_runs?.find(x=>x.path?.endsWith('/buildone.yml'))||null}let artifacts=[];if(run?.id){const x=await gh(`${GH}/repos/${o}/${r}/actions/runs/${run.id}/artifacts`,env.GITHUB_TOKEN);if(x.ok)artifacts=(await x.json()).artifacts||[]}const list=artifacts.map(a=>({id:a.id,name:a.name,size:a.size_in_bytes,expired:a.expired,digest:a.digest,runId:a.workflow_run?.id,headSha:a.workflow_run?.head_sha,type:/buildone-(APK|AAB)-/i.exec(a.name||'')?.[1]||null}));return {ok:true,run:run&&{id:run.id,status:run.status,conclusion:run.conclusion,sha:run.head_sha,url:run.html_url},artifacts:type?list.filter(a=>a.type===type):list}}
async function verifyAds(req){const u=new URL(req.url),domain=(u.searchParams.get('domain')||'').trim().toLowerCase(),pub=(u.searchParams.get('publisherId')||'').trim();if(!pubOk(pub)||!domainOk(domain)||privateHost(domain))throw Error('Invalid developer domain or publisher ID');const expected=`google.com, ${pub}, DIRECT, f08c47fec0942fa0`,url=`https://${domain}/app-ads.txt`;const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),10000);try{const r=await fetch(url,{redirect:'error',signal:ctl.signal,headers:{Accept:'text/plain','User-Agent':'BuildOne-app-ads-verifier/1.0'}});if(!r.ok)return {ok:true,verified:false,reason:`HTTP ${r.status}`,url};const text=await r.text();if(text.length>1048576)return {ok:true,verified:false,reason:'File exceeds 1 MB',url};const verified=text.split(/\r?\n/).some(x=>x.trim()===expected);return {ok:true,verified,reason:verified?'Exact publisher entry found':'Expected publisher entry not found',url};}finally{clearTimeout(timer)}}
async function artifact(req,env){const u=new URL(req.url),o=u.searchParams.get('owner'),r=u.searchParams.get('repo'),id=u.searchParams.get('artifact_id'),runId=u.searchParams.get('run_id'),type=u.searchParams.get('type');if(!o||!r||!/^[0-9]+$/.test(id)||!/^[0-9]+$/.test(runId)||!['APK','AAB'].includes(type))throw Error('Artifact parameters are incomplete');const ax=await gh(`${GH}/repos/${o}/${r}/actions/artifacts/${id}`,env.GITHUB_TOKEN);if(!ax.ok)throw Error(`artifact lookup failed: ${ax.status}`);const a=await ax.json();if(a.expired||a.size_in_bytes<=0)throw Error('Artifact is expired or empty');if(String(a.workflow_run?.id)!==String(runId))throw Error('Artifact/run ID mismatch');if(!new RegExp(`buildone-${type}-`,'i').test(a.name||''))throw Error('Artifact type mismatch');const rx=await gh(`${GH}/repos/${o}/${r}/actions/runs/${runId}`,env.GITHUB_TOKEN);if(!rx.ok)throw Error('Build run lookup failed');const run=await rx.json();if(run.conclusion!=='success')throw Error('Download blocked: build is not successful');if(a.workflow_run?.head_sha!==run.head_sha)throw Error('Download blocked: artifact/run commit mismatch');const x=await gh(`${GH}/repos/${o}/${r}/actions/artifacts/${id}/zip`,env.GITHUB_TOKEN);if(!x.ok)throw Error(`artifact download failed: ${x.status}`);return new Response(x.body,{headers:{...C,'content-type':'application/zip','content-disposition':`attachment; filename="buildone-${type}-verified.zip"`}})}
export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:C});try{if(env.BUILDONE_KEY&&req.headers.get('x-buildone-key')!==env.BUILDONE_KEY)return json({ok:false,error:'Unauthorized'},401);if(!env.GITHUB_TOKEN)return json({ok:false,error:'GITHUB_TOKEN is not configured'},500);const u=new URL(req.url);if(req.method==='POST'&&u.pathname==='/build')return json(await build(req,env),202);if(req.method==='GET'&&u.pathname==='/status')return json(await status(req,env));if(req.method==='GET'&&u.pathname==='/artifact')return artifact(req,env);if(req.method==='GET'&&u.pathname==='/verify-app-ads-txt')return json(await verifyAds(req));if(req.method==='GET'&&u.pathname==='/health')return json({ok:true,service:'BuildOne Worker v2',artifactGate:'strict',adsVerification:true});return json({ok:true,service:'BuildOne Worker v2',admob:ADS});}catch(e){return json({ok:false,error:e.message||String(e)},400)}}};
